name: Deploy Updates

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Backup:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
      - shell: cmd
        env:
          GIT_EMAIL: ${{ secrets.EMAIL }}
          GIT_NAME: ${{ secrets.NAME }}
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: Setup Git
        run: |
          git config --global user.email "%GIT_EMAIL%"
          git config --global user.name "%GIT_NAME%"
      - name: Install Packages
        run: |
          cd personal-portfolio
          CI=false npm install --dev
      - name: Deploy
        run: |
          cd personal-portfolio
          CI=false npm run deploy -- -m "Deploy React app to GitHub Pages"
