name: Deploy Updates

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    timeout-minutes: 120
    
    steps:
      - name: Update Repo
        run: |
          cd ../../../TheByrdSpot
          git pull
      - name: Setup Git Config
        run: |
          cd ../../../TheByrdSpot
          ls -a
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Install Packages
        run: |
          cd ../../../TheByrdSpot
          ls -a
          cd personal-portfolio
          CI=false npm install --dev
      - name: Deploy
        run: |
          cd ../../../TheByrdSpot
          ls -a
          cd personal-portfolio
          CI=false npm run deploy -- -m "Deploy React app to GitHub Pages"
